sudo: required

services:
  - docker

before_install:
  - docker build -t lekhrajdeshmukh/myReactApp -f Dockerfile.dev

script:
  - docker run -e CI=true lekhrajdeshmukh/myReactApp np run test


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-ci"
  env: "dockerci-env"
  bucket_name: "elasticbeanstalk-us-east-1-638657333560"
  bucket_path: "docker-ci"
  on:
    branch: master